name: vscode publish

on:
  pull_request:
    types:
      - "closed"
    branches:
<<<<<<< HEAD
=======
      - "main"
>>>>>>> main
      - "release/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: ll
