name: VSCode Publish

on:
  release:
    types:
      - "released"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Setup Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 16

      # - name: Install Dependencies
      #   run: yarn

      # - name: Bundle
      # run: yarn package
      - name: Get Name
        id: get_name
        run: echo NAME=$(jq -r .name package.json) >> $GITHUB_OUTPUT

      - name: Get Version
        id: get_version
        run: echo VERSION=$(jq -r .version package.json) >> $GITHUB_OUTPUT

      - run: echo 'hello world' > ${{steps.get_name.outputs.NAME}}-${{steps.get_version.outputs.VERSION}}.txt

      - uses: nebula-actions/upload-assets
        with:
          asset-path: "${{steps.get_name.outputs.NAME}}-${{steps.get_version.outputs.VERSION}}.txt"
