name: VSCode Publish

on:
  release:
    types:
      - "released"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Setup Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 16

      # - name: Install Dependencies
      #   run: yarn

      # - name: Bundle
      # run: yarn package
      - run: echo 'hello world' > hello.txt

  # release:
  #   name: Release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  # - name: Get Name
  #   id: get_name
  #   run: echo NAME=$(jq -r .name package.json) >> $GITHUB_OUTPUT

  # - name: Get Version
  #   id: get_version
  #   run: echo VERSION=$(jq -r .version package.json) >> $GITHUB_OUTPUT

  # - name: Upload Artifact
  #   uses: actions/upload-artifact@v3
  #   with:
  #     name: vsix
  #     path: ${{steps.get_name.outputs.NAME}}-${{steps.get_version.outputs.VERSION}}.vsix
  #     retention-days: 5

  # - name: Download Artifact
  #   uses: actions/download-artifact@v3
  #   with:
  #     name: my-artifact

  # - name: Publish to Visual Studio Marketplace
  #   uses: HaaLeo/publish-vscode-extension@v1
  #   with:
  #     yarn: true
  #     pat: ${{ secrets.VSCE_PAT }}
  #     registryUrl: https://marketplace.visualstudio.com
