name: VSCode Publish

on:
  release:
    types:
      - "released"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Setup Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 16

      # - name: Install Dependencies
      #   run: yarn

      # - name: Bundle
      # run: yarn package
      - name: Get Name
        id: get_name
        run: echo NAME=$(jq -r .name package.json) >> $GITHUB_OUTPUT

      - name: Get Version
        id: get_version
        run: echo VERSION=$(jq -r .version package.json) >> $GITHUB_OUTPUT

      - run: echo 'hello world' > ${{steps.get_name.outputs.NAME}}-${{steps.get_version.outputs.VERSION}}.txt

      - name: Create Release
        id: release
        uses: halvardssm/github-action-tag-release@v1
        with:
          token: ${{ secrets.GH_PAT }}
          path: "./package.json" # optional, will use ./package.json by default
      - run: |
          echo 'Release exists: ${{steps.version.outputs.release_exists}}' # 'true' or 'false'
          echo 'Release tag: ${{steps.version.outputs.release_tag}}' # The tag from package.json
      - if: ${{steps.release.outputs.release_exists == 'true'}}
        run: |
          echo ${{steps.release.outputs.release_tag}} > ${{steps.get_name.outputs.NAME}}-${{steps.get_version.outputs.VERSION}}.txt

      - uses: echapmanFromBunnings/upload-release-assets@1.3
        with:
          releaseTag: ${{steps.release.outputs.release_tag}}
          githubToken: ${{ secrets.GH_PAT }}
          files: |
            ${{steps.get_name.outputs.NAME}}-${{steps.get_version.outputs.VERSION}}.txt
